baseurl: "/"
languageCode: "en-us"
title: "A minimal+ Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:slug/"
  post: "/post/:year/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4

params:
  description: "A website built through Hugo and blogdown."
  GithubEdit: "https://github.com/drizmiz/blog/edit/main/content/"
  footer: "[CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0) | &#127279; [Drizzle](https://driz.netlify.app)"

markup:
  goldmark:
    renderer:
      unsafe: true
